# NumPy

NumPy (formerly known as Numerical Python) is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code (It uses Fortan's LAPACK linear algebra library)
- useful for mathematical operations in the fields of linear algebra, Fourier transform, and random number generation,
  probability and statistics

It added C-like data structures like arrays of atomic objects as magnificent tools to Python for scientific computation. 

Library documentation: <a>http://www.numpy.org/</a>

In [1]:
import numpy as np

In [2]:
# declare a vector using a list as the argument
v = np.array([1,2,3,4], dtype=np.float64)
v

a = np.random.randn(1000000)
b = np.random.randn(1000000)

np.dot(a, b)

-497.4838996739681

In [3]:
# declare a matrix using a nested list as the argument
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [4]:
# still the same core type with different shapes
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

In [5]:
np.shape(M)

(2, 2)

In [6]:
# arguments: start, stop, step
x = np.arange(0, 10, 1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(0, 10, 25)

array([  0.        ,   0.41666667,   0.83333333,   1.25      ,
         1.66666667,   2.08333333,   2.5       ,   2.91666667,
         3.33333333,   3.75      ,   4.16666667,   4.58333333,
         5.        ,   5.41666667,   5.83333333,   6.25      ,
         6.66666667,   7.08333333,   7.5       ,   7.91666667,
         8.33333333,   8.75      ,   9.16666667,   9.58333333,  10.        ])

In [8]:
from numpy import random

In [9]:
random.rand(10,5)
random.uniform(2, 20, 4)

array([ 9.27485755,  5.5943088 ,  7.66552264,  8.44108468])

In [10]:
# normal distribution
random.randn(5, 5)

array([[  2.48615190e-01,   1.04493210e+00,  -1.25778666e+00,
          2.35901528e-01,  -1.61877747e+00],
       [ -5.03084487e-01,   5.56559859e-02,   1.18194929e+00,
         -8.88277929e-04,  -4.88419045e-01],
       [ -3.48841835e-01,  -2.15876407e+00,  -1.35405102e+00,
         -1.16260444e+00,   1.45245230e+00],
       [ -6.32789060e-01,   2.51816607e-01,   8.29568448e-03,
         -4.65883977e-01,   1.85538878e+00],
       [  6.42205011e-01,  -3.56880219e-01,  -6.47918904e-01,
          1.17230193e+00,  -1.72749070e+00]])

In [11]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [12]:
print(M)
M[0, :] = 0
M

[[1 2]
 [3 4]]


array([[0, 0],
       [3, 4]])

In [15]:
# slicing works just like with lists
A = np.array([1, 2, 3, 4, 5])
A[1:3]

array([2, 3])

In [16]:
A = np.array([[n + m * 10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [17]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [20]:
# index masking
B = np.array([n for n in range(5)])
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

### Linear Algebra

In [21]:
v1 = np.arange(0, 5)
print(v1)

[0 1 2 3 4]


In [22]:
v1 = v1 + 2
print(v1)

[2 3 4 5 6]


In [23]:
v1 * 2
np.power(v1, 2)

array([ 4,  9, 16, 25, 36])

In [24]:
v1 * v1

array([ 4,  9, 16, 25, 36])

In [25]:
np.dot(v1, v1)

90

In [26]:
print(A)
np.dot(A, v1)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


array([ 50, 250, 450, 650, 850])

In [27]:
# cast changes behavior of + - * etc. to use matrix algebra
M = np.matrix(A)
M * M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [28]:
# inner product
v.T * v

array([  1.,   4.,   9.,  16.])

In [29]:
C = np.matrix([[1j, 2j], [3j, 4j]])
C

matrix([[ 0.+1.j,  0.+2.j],
        [ 0.+3.j,  0.+4.j]])

In [30]:
np.conjugate(C)

matrix([[ 0.-1.j,  0.-2.j],
        [ 0.-3.j,  0.-4.j]])

In [31]:
# inverse
C.I

matrix([[ 0.+2.j ,  0.-1.j ],
        [ 0.-1.5j,  0.+0.5j]])

### Statistics

In [32]:
print(A)
np.mean(A[:,3])

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


23.0

In [33]:
print(A[:,3])
np.std(A[:,3]), np.var(A[:,3])

[ 3 13 23 33 43]


(14.142135623730951, 200.0)

In [34]:
A[:,3].min(), A[:,3].max(), np.min(A[:,3]), np.max(A[:,3])

(3, 43, 3, 43)

In [35]:
d = np.arange(1, 10)
sum(d), np.prod(d), np.sum(d)

(45, 362880, 45)

In [36]:
np.cumsum(d)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [37]:
np.cumprod(d)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [38]:
# sum of diagonal
np.trace(A)

110

In [39]:
m = random.rand(3, 3)
m

array([[ 0.03898144,  0.02350252,  0.69019084],
       [ 0.188873  ,  0.53062048,  0.2717752 ],
       [ 0.52746531,  0.84245563,  0.04078469]])

In [40]:
# use axis parameter to specify how function behaves
m.max(), m.max(axis=1), np.mean(m, axis=0)

(0.84245562508556526,
 array([ 0.69019084,  0.53062048,  0.84245563]),
 array([ 0.25177325,  0.46552621,  0.33425024]))

In [41]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [42]:
# reshape without copying underlying data
n, m = A.shape
B = A.reshape((1,n * m))

B

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
        32, 33, 34, 40, 41, 42, 43, 44]])

In [43]:
# modify the array
B[0,0:5] = 5
B

array([[ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
        32, 33, 34, 40, 41, 42, 43, 44]])

In [44]:
v = [4, 5 ]
np.repeat(v, 3)

array([4, 4, 4, 5, 5, 5])

In [45]:
np.tile(v, 3)

array([4, 5, 4, 5, 4, 5])

In [46]:
w = np.array([5, 6])

In [47]:
np.concatenate((v, w), axis=0)
print(v)
print(w)

[4, 5]
[5 6]
